# dbmate requires 'pg_dump' to be installed
FROM postgres:12

# Install dbmate
ADD https://github.com/amacneil/dbmate/releases/download/v1.4.1/dbmate-linux-amd64 /usr/local/bin/dbmate
RUN chmod +x /usr/local/bin/dbmate
